# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Memeful' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Memeful
  pod 'SwiftMessages'
  pod 'IQKeyboardManagerSwift', '~> 6.0.4'
  pod 'Alamofire'
  pod 'MBProgressHUD'
  pod 'Kingfisher'
  pod "KRPullLoader"
  pod 'MMPlayerView'

end
